#!/usr/bin/env python3
import os
from place_bot import Placer, Color
from pprint import pprint
import random
import requests
from time import sleep


class LoginError(Exception):
    pass


class PlaceError(Exception):
    pass


username = os.environ["REDDIT_USER"]
password = os.environ["REDDIT_PW"]
cfg_url = "https://raw.githubusercontent.com/stingray300k/placebot/vim/out.cfg"

placer = Placer()

print("logging in... ", end="")
try:
    placer.login(username, password)
except AssertionError as e:
    raise LoginError("error while logging in") from e
print("done")

while True:
    print("downloading target image config... ", end="")
    pixels_cfg = requests.get(cfg_url).json()["pixels"]
    print("done")

    pixel_cfg = random.choice(pixels_cfg)
    place_tile_kwargs = {
        "x": pixel_cfg["x"],
        "y": pixel_cfg["y"],
        "color": Color.from_id(pixel_cfg["color_index"]),
    }
    print("will try to draw tile:")
    pprint(pixel_cfg)

    print("placing tile... ", end="")
    try:
        placer.place_tile(**place_tile_kwargs)
    except AssertionError as e:
        raise PlaceError("error while placing tile") from e
    print("done")

    print("sleeping for 21 minutes")
    sleep(21 * 60)
